/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.fluxo;

import components.JCampoBusca;
import java.awt.event.ActionEvent;
import components.JPanelControleButtons;

import components.JTableDataBinderListener;
import java.util.Collection;
import javassist.bytecode.analysis.Util;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import model.fluxo.Conta;
import model.fluxo.ContaCategoria;
import model.fluxo.Parcela;
import services.ServiceException;
import services.fluxo.ContaService;
import utils.Globals;
import utils.Utils;

/**
 *
 * @author Charles
 */
public class FrmConta extends JPanelControleButtons {

    private final ContaService service;
//    JTableDataBinder table;

    public FrmConta() {
        initComponents();
        setBtnAddEnable(true);
        setBtnAlterarEnable(true);
        setBtnExcluirEnable(true);
        setBtnAtualizarEnable(true);

        service = new ContaService();

        table.setListener(new JTableDataBinderListener<Conta>() {

            @Override
            public Collection<Conta> lista(String busca) throws ServiceException {

                return service.findContas(busca, jcbContasAPagar.isSelected(),jcbContasAReceber.isSelected());

            }

            @Override
            public Object[] addRow(Conta dado) {
                ImageIcon i = null;
                for (Parcela parcela : dado.getParcelas()) {
                    if (!parcela.isFechado()) {
                        i = Globals.iconeError;
                        break;
                    }

                }
                if (i == null) {
                    i = Globals.iconeSuccess;
                }
                Object[] obj = new Object[8];
                obj[0] = dado.getId();
                obj[1] = dado.getDescricao();
                obj[2] = dado.getPessoa().getNome();
                obj[3] = dado.getCategoria().getTipo() == ContaCategoria.TipoCategoria.entrada ? "A Receber" : "A Pagar";
                obj[4] = Utils.formataDinheiro(ContaService.valorConta(dado));
                obj[5] = dado.getCategoria().toString();
                obj[6] = i;

                return obj;

            }
        });

        table.setBusca(txtBuscar, true);
        table.atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new components.JTableDataBinder();
        txtBuscar = new components.JTextFieldUpper(true);
        jLabel2 = new javax.swing.JLabel();
        jcbContasAPagar = new javax.swing.JCheckBox();
        jcbContasAReceber = new javax.swing.JCheckBox();
        btnPagamento = new javax.swing.JButton();
        btnParcelas = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Pessoa Relacionada", "Tipo", "Valor", "Categoria", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setBusca(txtBuscar);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(10);
            table.getColumnModel().getColumn(0).setPreferredWidth(60);
            table.getColumnModel().getColumn(0).setMaxWidth(100);
            table.getColumnModel().getColumn(6).setPreferredWidth(30);
            table.getColumnModel().getColumn(6).setMaxWidth(30);
        }

        jLabel2.setText("Buscar:");

        jcbContasAPagar.setSelected(true);
        jcbContasAPagar.setText("A Pagar");
        jcbContasAPagar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbContasAPagarStateChanged(evt);
            }
        });

        jcbContasAReceber.setSelected(true);
        jcbContasAReceber.setText("A Receber");
        jcbContasAReceber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbContasAReceberStateChanged(evt);
            }
        });

        btnPagamento.setText("Pagamento");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });

        btnParcelas.setText("Parcelas");
        btnParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbContasAPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbContasAReceber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParcelas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbContasAPagar)
                    .addComponent(jcbContasAReceber)
                    .addComponent(btnPagamento)
                    .addComponent(btnParcelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        defaultUpdateOperation(table, (id) -> {
            
            Conta c = service.findConta(id);
            FrmParcelaPagamentoCadastro frm = new FrmParcelaPagamentoCadastro(c);
            frm.setListener((conta)->{
                service.update(c);
                table.atualizar();
            });
            frm.setVisible(true);
        });

    }//GEN-LAST:event_btnPagamentoActionPerformed

    private void btnParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelasActionPerformed
         defaultUpdateOperation(table, (id) -> {
            
            Conta c = service.findConta(id);
            FrmParcelaCadastro frm = new FrmParcelaCadastro(c, c.getParcelas().get(0));
            frm.setListener((conta)->{
                service.update(c);
                table.atualizar();
            });
            frm.setVisible(true);
        });

    }//GEN-LAST:event_btnParcelasActionPerformed

    private void jcbContasAReceberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbContasAReceberStateChanged
        table.atualizar();
    }//GEN-LAST:event_jcbContasAReceberStateChanged

    private void jcbContasAPagarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbContasAPagarStateChanged
        table.atualizar();
    }//GEN-LAST:event_jcbContasAPagarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnParcelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcbContasAPagar;
    private javax.swing.JCheckBox jcbContasAReceber;
    private components.JTableDataBinder table;
    private components.JTextFieldUpper txtBuscar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void btnAddActionPerformed(ActionEvent evt) {
//        model.createNew();
        JDialog dialog = new FrmContaCadastro();
        dialog.setVisible(true);
        table.atualizar();
    }

    @Override
    public void btnAlterarActionPerformed(ActionEvent evt) {
        defaultUpdateOperation(table, (i) -> {
            JDialog dialog = new FrmContaCadastro(i);
            dialog.setVisible(true);
        });

    }

    @Override
    public void btnExcluirActionPerformed(ActionEvent evt) {
        defaultDeleteOperation(table, (i) -> service.delete(i));
    }

    @Override
    public void btnAtualizarActionPerformed(ActionEvent evt) {
        table.atualizar();
    }
}
