/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.ordem;

import components.JDialogController;
import components.ThrowingCommand;
import forms.fluxo.FrmContaCadastro;
import forms.frmMain;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.fluxo.Conta;
import model.fluxo.ContaCategoria;
import model.ordem.Marca;
import model.ordem.Ordem;
import model.ordem.OrdemServico;
import model.ordem.OrdemTipoServico;
import services.ServiceException;
import services.fluxo.ContaService;
import services.ordem.OrdemServicoService;

import services.ordem.MarcaService;
import services.ordem.OrdemTipoServicoService;
import utils.AlertaTipos;
import utils.Forms;
import utils.Parametros;
import utils.Utils;

/**
 *
 * @author Charles
 */
public class FrmOrdemServicoCadastro extends JDialogController {

    private Ordem ordem;
    private final OrdemServicoService service = new OrdemServicoService();

    public FrmOrdemServicoCadastro(Ordem ordem) {
        super(frmMain.getInstance(), "Manutenção de Serviços");
        initComponents();
        this.ordem = ordem;
        setupForm();
    }

    private void setupForm() {
        // center the jframe on screen
        setLocationRelativeTo(null);
        setDefaultButton(btnSalvar);
        jcbTerceiro.setSelected(false);
        jcbServico.setModel(new DefaultComboBoxModel(new Vector(new OrdemTipoServicoService().findAtivos())));
        if (jcbServico.getModel().getSize() == 0) {
            Forms.mensagem("Cadastre um tipo de serviço primeiro", AlertaTipos.erro);
            throw new ServiceException("Cadastre um tipo de serviço primeiro", null);
        }
        atualizaValor();

    }

    private void atualizaValor() {
        OrdemTipoServico tipo = (OrdemTipoServico) jcbServico.getSelectedItem();
        txtValor.setValue(tipo.getValorEntrada());
        atualizaValorTotal();
    }

    private double getValorTotal() {
        double v = txtValor.getValue() * ((Integer) txtQuantidade.getValue() + 0d);
        return v;
    }

    private void atualizaValorTotal() {
        lblValorTotal.setText(Utils.formataDinheiro(getValorTotal()));

    }

    private void save() {
        if (!validator.isValido()) {
            return;
        }
        OrdemServico m;
        m = new OrdemServico();
        m.setValorEntrada(txtValor.getValue());
        m.setDataRealizada(txtData.getDate());
        m.setOrdem(ordem);
        m.setTipoServico((OrdemTipoServico) jcbServico.getSelectedItem());
        m.setQuantidade((Integer) txtQuantidade.getValue());
        ThrowingCommand command = () -> {

            service.insert(m);
            ordem.getOrdemServicos().add(m);

            dispose();
        };
        if (jcbTerceiro.isSelected()) {
            Conta c;
            if (!txtNotaFiscal.getText().trim().equals("") && (c = new ContaService().findByNota(txtNotaFiscal.getText().trim())) != null) {
                m.setConta(c);
                command.action();
            } else {
                FrmContaCadastro frm = new FrmContaCadastro(getValorTotal(), 1, txtNotaFiscal.getText(), Conta.ContaTipo.conta, ContaCategoria.TipoCategoria.saida);
                frm.setDescricao("SERVIÇO DE TERCEIRO RELACIONAO A ORDEM DE SERVIÇO " + ordem.getId());
                frm.setCategoria(new ContaCategoria(Integer.valueOf(Parametros.getInstance().getValue("categoria_terceiros"))));
                frm.setListenerOnSave((conta) -> {
                    m.setConta(conta);
                    command.action();
                });
                frm.setVisible(true);
            }

        } else {
            command.action();
        }
//        if (id > 0) {
//            m = service.findById(id);
//        } else {
//            m = new OrdemServico();
//        }
////        m.setNome(txtNome.getText());
////        m.setMarca(new Marca(txtMarca.getValueSelected()));
//        Utils.safeCode(() -> {
//            if (id == 0) {
//                service.insert(m);
//            } else {
//                service.update(m);
//            }
//            utils.Forms.mensagem(utils.Mensagens.registroSalvo, AlertaTipos.sucesso);
//
//            dispose();
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jcbServico = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new components.JTextFieldMoney();
        jLabel4 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jcbTerceiro = new javax.swing.JCheckBox();
        txtNotaFiscal = new components.PlaceholderTextField();
        txtData = new components.JDateField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Serviço:");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jcbServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carregando..." }));
        jcbServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbServicoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Quantidade:");

        txtQuantidade.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        txtQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtQuantidadeStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Valor Unitário:");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Valor Total:");

        lblValorTotal.setText("R$0,00");

        jcbTerceiro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTerceiro.setText("Serviço Terceirizado");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtNotaFiscal, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jcbTerceiro, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jcbTerceiro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbTerceiroStateChanged(evt);
            }
        });

        txtNotaFiscal.setPlaceholder("Número da Nota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValorTotal)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcbTerceiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jcbServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 584, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbServico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTerceiro)
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        save();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jcbTerceiroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbTerceiroStateChanged
//        txtNotaFiscal.setVisible(jcbTerceiro.isSelected());
    }//GEN-LAST:event_jcbTerceiroStateChanged

    private void jcbServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbServicoActionPerformed
        atualizaValor();
    }//GEN-LAST:event_jcbServicoActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        atualizaValorTotal();
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtQuantidadeStateChanged
        atualizaValorTotal();
    }//GEN-LAST:event_txtQuantidadeStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcbServico;
    private javax.swing.JCheckBox jcbTerceiro;
    private javax.swing.JLabel lblValorTotal;
    private components.JDateField txtData;
    private components.PlaceholderTextField txtNotaFiscal;
    private javax.swing.JSpinner txtQuantidade;
    private components.JTextFieldMoney txtValor;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
